nodeLinker: node-modules

npmScopes:
  plentymarkets:
    npmAuthToken: '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'
    npmRegistryServer: 'https://npm.pkg.github.com'

# used for upgrading packages, terminal comand:
# yarn upgrade-interactive
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.6.4.cjs
